Time::DATE_FORMATS[:feedback] = '%m-%d-%Y %l:%M%P'
Time::DATE_FORMATS[:pretty] = '%a %b %-d, %Y %l:%M%P'
Time::DATE_FORMATS[:time] = '%l:%M%P'
Time::DATE_FORMATS[:day_and_month] = '%a %b %-d'
Time::DATE_FORMATS[:slashes] = '%-m/%-d/%Y'