development:
  adapter: postgresql
  encoding: utf8
  database: fittfu_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: fittfu_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: fittfu_production
  pool: 5
  username:
  password:
